// <auto-generated />
using DanielDevDojo.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DanielDevDojo.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DanielDevDojo.Shared.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 18,
                            FirstName = "Bob",
                            LastName = "Wakefield",
                            Location = "London"
                        },
                        new
                        {
                            Id = 2,
                            Age = 18,
                            FirstName = "Lisa",
                            LastName = "Manda",
                            Location = "Dee"
                        },
                        new
                        {
                            Id = 3,
                            Age = 18,
                            FirstName = "Bob",
                            LastName = "Wakefield",
                            Location = "London"
                        },
                        new
                        {
                            Id = 4,
                            Age = 26,
                            FirstName = "Victor",
                            LastName = "Crest",
                            Location = "London"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
